### ISSUE TITLE
client在linux运行一段时间会占用CPU100%

### ISSUE THREAD

**Issue by youguangbin** [PlainJi/Desktop-Computer-Monitor#1]
client在linux运行一段时间会占用CPU100%，界面不刷新，不知是否有遇到相同问题。运行过程有在PC上py脚本发送json数据过去。不发json数据好像没有出现卡死。

**Comment by PlainJi** [comment]
可能是因为之前没有给 **lv_** 相关的函数加锁导致的，V2版本经过长时间测试没有发现此问题。
